### ISSUE TITLE
Subtitles background transparency issue.

### ISSUE THREAD

**Issue by Rozin14** [IDimitrovDev/Energy-Media-Player#6]
Subtitles background doesn't get affected by transparency slider. A black background is always visible.

**Comment by IDimitrovDev** [comment]
Thank you for reporting the issue. It seem like an windows update has broken up default subtitles support making it that any change in `Accessibility -> Captions` disables the default subtitles functionality and replaces it with the defaults configured in the `Default` theme which has hardcoded values for text and background that cannot be overridden to  defaults. According to the reported [ issue](https://github.com/microsoft/microsoft-ui-xaml/issues/9126) SettingsUI team is looking into the issue. Meanwhile possible workarounds are using the windows settings to set color/background/font, etc instead of the internal player settings or manually removing the overridden registry keys with powershell to get to initial state (preferably with backing up the registry before running the command)

` Remove-Item -Path Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning`

**Comment by IDimitrovDev** [comment]
Or a new correct default theme can be generated with the following powershell script
```
New-Item -Path Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme -Name '{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name BackgroundColor -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name BackgroundTransparency -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name CaptionColor -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name CaptionEffects -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name CaptionSize -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name CaptionTransparency -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name ThemeName -Value 'Real default' -PropertyType String -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name WindowColor -Value 0 -PropertyType DWORD -Force
New-ItemProperty -Path 'Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ClosedCaptioning\Theme\{2759ef05-cb91-46f3-a7d0-7ad474a94c34}' -Name WindowTransparency -Value 0 -PropertyType DWORD -Force
```
 After which it can be selected from the Caption settings as 'Real default'
![image](https://github.com/IDimitrovDev/Energy-Media-Player/assets/70667043/2236293b-b276-44bd-9847-5d45f2b0e1d3)

**Comment by IDimitrovDev** [comment]
Starting from version v217 a new subtitle renderer has been added to the player, which is enabled by default and fixes the issues using the system renderer with colors not changing. The old system renderer can be re-enabled from the subtitle settings if needed. The new renderer also fixes issue with changing subtitle settings, but seeing the changes only on next subtitle instead of immediately and also enables color configurations for XBOX, which was previously impossible with the system renderer.
